//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carts
    {
        public Carts()
        {
            this.CartItems = new HashSet<CartItems>();
        }
    
        public int CartID { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<CartItems> CartItems { get; set; }
        public virtual Users Users { get; set; }
    }
}
