//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Client_ID { get; set; }
        public string Name { get; set; }
        public int SparePart_ID { get; set; }
        public int Result { get; set; }
    
        public virtual SparePart SparePart { get; set; }
    }
}
