//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pr7Entities : DbContext
    {
        public pr7Entities()
            : base("name=pr7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AutoService> AutoService { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<SparePart> SparePart { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
