//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public int ID { get; set; }
        public Nullable<int> Tovar { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual zapch zapch { get; set; }
    }
}
